"""fixed table name

Revision ID: 07714bcde7f0
Revises: 22169d6bcb83
Create Date: 2026-04-06 22:34:04.478225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07714bcde7f0'
down_revision = '22169d6bcb83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donor_health',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('has_hiv', sa.Boolean(), nullable=False),
    sa.Column('has_hepatitis_b', sa.Boolean(), nullable=False),
    sa.Column('has_hepatitis_c', sa.Boolean(), nullable=False),
    sa.Column('has_syphilis', sa.Boolean(), nullable=False),
    sa.Column('has_malaria', sa.Boolean(), nullable=False),
    sa.Column('has_diabetes', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('donor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['donor_id'], ['donor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('donor_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('donor_health')
    # ### end Alembic commands ###
