"""remove name from blood_banks

Revision ID: 17b284b8910e
Revises: 2f8e36d89b7e
Create Date: 2026-04-28 16:11:55.731935

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '17b284b8910e'
down_revision = '2f8e36d89b7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blood_banks', schema=None) as batch_op:
        batch_op.alter_column('license_number',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blood_banks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=100), nullable=True))
        batch_op.alter_column('license_number',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###
