"""created donor_health table

Revision ID: 22169d6bcb83
Revises: ee6e31c6f125
Create Date: 2026-04-06 22:21:50.386021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22169d6bcb83'
down_revision = 'ee6e31c6f125'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donor__health',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('has_hiv', sa.Boolean(), nullable=False),
    sa.Column('has_hepatitis_b', sa.Boolean(), nullable=False),
    sa.Column('has_hepatitis_c', sa.Boolean(), nullable=False),
    sa.Column('has_syphilis', sa.Boolean(), nullable=False),
    sa.Column('has_malaria', sa.Boolean(), nullable=False),
    sa.Column('has_diabetes', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('donor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['donor_id'], ['donor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('donor_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('donor__health')
    # ### end Alembic commands ###
