"""remove has_hospital

Revision ID: 2f8e36d89b7e
Revises: 6f86500b6fb3
Create Date: 2026-04-28 14:56:12.188991

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2f8e36d89b7e'
down_revision = '6f86500b6fb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blood_banks', schema=None) as batch_op:
        batch_op.drop_column('has_hospital')
        batch_op.drop_column('hospital_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blood_banks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hospital_name', mysql.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('has_hospital', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
