"""remove userID FK in stock table

Revision ID: 375880891659
Revises: 9d54b2d19f1e
Create Date: 2026-04-30 14:52:51.027050

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '375880891659'
down_revision = '9d54b2d19f1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blood_stock', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('blood_stock_ibfk_2'), type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blood_stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('blood_stock_ibfk_2'), 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
