"""gender field changed to donor table from user

Revision ID: 39ed7d739d02
Revises: 76ef83ca0876
Create Date: 2025-12-22 11:55:44.486927

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '39ed7d739d02'
down_revision = '76ef83ca0876'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=20), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('gender')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', mysql.VARCHAR(length=20), nullable=True))

    with op.batch_alter_table('donor', schema=None) as batch_op:
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
