"""add bloodbank city again

Revision ID: 40e9d02b0e36
Revises: c69e3872a061
Create Date: 2026-04-28 19:25:26.386431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40e9d02b0e36'
down_revision = 'c69e3872a061'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blood_banks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blood_banks', schema=None) as batch_op:
        batch_op.drop_column('city')

    # ### end Alembic commands ###
