"""remove health cured logic again

Revision ID: 5328ebd9daac
Revises: bb2fff018941
Create Date: 2026-04-30 18:57:19.223269

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5328ebd9daac'
down_revision = 'bb2fff018941'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donor_health', schema=None) as batch_op:
        batch_op.drop_column('syphilis_cured_date')
        batch_op.drop_column('syphilis_cured')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donor_health', schema=None) as batch_op:
        batch_op.add_column(sa.Column('syphilis_cured', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('syphilis_cured_date', sa.DATE(), nullable=True))

    # ### end Alembic commands ###
