"""added bloodbank... tables and is_verified column

Revision ID: 6f86500b6fb3
Revises: 7dc58b7241c9
Create Date: 2026-04-28 13:10:11.174598

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6f86500b6fb3'
down_revision = '7dc58b7241c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blood_banks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('helpline_number', sa.String(length=15), nullable=True),
    sa.Column('license_number', sa.String(length=50), nullable=True),
    sa.Column('has_hospital', sa.Boolean(), nullable=False),
    sa.Column('hospital_name', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blood_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('bloodbank_id', sa.Integer(), nullable=True),
    sa.Column('blood_type', sa.String(length=5), nullable=True),
    sa.Column('quantity_ml', sa.Integer(), nullable=True),
    sa.Column('patient_name', sa.String(length=100), nullable=True),
    sa.Column('hospital_name', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('request_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bloodbank_id'], ['blood_banks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blood_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bloodbank_id', sa.Integer(), nullable=True),
    sa.Column('blood_type', sa.String(length=5), nullable=True),
    sa.Column('quantity_ml', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bloodbank_id'], ['blood_banks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('donor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('availability', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('last_donation_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('total_donations', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_quantity_ml', sa.Integer(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))
        batch_op.alter_column('role',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.drop_column('is_verified')

    with op.batch_alter_table('donor', schema=None) as batch_op:
        batch_op.drop_column('last_quantity_ml')
        batch_op.drop_column('total_donations')
        batch_op.drop_column('last_donation_date')
        batch_op.drop_column('availability')

    op.drop_table('blood_stock')
    op.drop_table('blood_requests')
    op.drop_table('blood_banks')
    # ### end Alembic commands ###
