"""add malaria

Revision ID: 77003f5ba731
Revises: ab84bd4f282a
Create Date: 2026-04-30 19:06:24.364740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77003f5ba731'
down_revision = 'ab84bd4f282a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donor_health', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_malaria', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donor_health', schema=None) as batch_op:
        batch_op.drop_column('has_malaria')

    # ### end Alembic commands ###
