"""add contact number in request

Revision ID: 7992ce8ce180
Revises: 40e9d02b0e36
Create Date: 2026-04-28 21:26:42.992829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7992ce8ce180'
down_revision = '40e9d02b0e36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blood_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact', sa.String(length=15), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blood_requests', schema=None) as batch_op:
        batch_op.drop_column('contact')

    # ### end Alembic commands ###
