"""added eligibility data in donor_health

Revision ID: 7dc58b7241c9
Revises: 07714bcde7f0
Create Date: 2026-04-10 20:59:28.639264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dc58b7241c9'
down_revision = '07714bcde7f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donor_health', schema=None) as batch_op:
        batch_op.add_column(sa.Column('syphilis_cured', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('syphilis_cured_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('malaria_cured', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('malaria_cured_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donor_health', schema=None) as batch_op:
        batch_op.drop_column('malaria_cured_date')
        batch_op.drop_column('malaria_cured')
        batch_op.drop_column('syphilis_cured_date')
        batch_op.drop_column('syphilis_cured')

    # ### end Alembic commands ###
