"""add district to donor

Revision ID: 80e47ebc2421
Revises: 77003f5ba731
Create Date: 2026-04-30 20:08:45.608462

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '80e47ebc2421'
down_revision = '77003f5ba731'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('district', sa.String(length=50), nullable=True))
        batch_op.alter_column('city',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donor', schema=None) as batch_op:
        batch_op.alter_column('city',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('district')

    # ### end Alembic commands ###
