"""add unique constraints

Revision ID: a39fc70f6afa
Revises: 7992ce8ce180
Create Date: 2026-04-29 15:24:14.001225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a39fc70f6afa'
down_revision = '7992ce8ce180'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blood_stock', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_blood_per_bank', ['bloodbank_id', 'blood_type'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blood_stock', schema=None) as batch_op:
        batch_op.drop_constraint('unique_blood_per_bank', type_='unique')

    # ### end Alembic commands ###
