"""remove time Stamp

Revision ID: ab84bd4f282a
Revises: 5328ebd9daac
Create Date: 2026-04-30 19:04:16.387140

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ab84bd4f282a'
down_revision = '5328ebd9daac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blood_requests', schema=None) as batch_op:
        batch_op.alter_column('request_date',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)

    with op.batch_alter_table('donor_health', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donor_health', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_nullable=False)

    with op.batch_alter_table('blood_requests', schema=None) as batch_op:
        batch_op.alter_column('request_date',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
