"""remove health cured logic

Revision ID: bb2fff018941
Revises: 375880891659
Create Date: 2026-04-30 18:56:14.747462

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bb2fff018941'
down_revision = '375880891659'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donor_health', schema=None) as batch_op:
        batch_op.drop_column('malaria_cured')
        batch_op.drop_column('malaria_cured_date')
        batch_op.drop_column('has_malaria')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donor_health', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_malaria', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('malaria_cured_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('malaria_cured', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
