"""remove last_quantity_ml

Revision ID: bdd59ed9d634
Revises: 80e47ebc2421
Create Date: 2026-04-30 20:10:50.262361

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bdd59ed9d634'
down_revision = '80e47ebc2421'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donor', schema=None) as batch_op:
        batch_op.drop_column('last_quantity_ml')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_quantity_ml', mysql.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
