"""remove bloodbank city

Revision ID: c69e3872a061
Revises: 17b284b8910e
Create Date: 2026-04-28 18:46:17.713712

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c69e3872a061'
down_revision = '17b284b8910e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blood_banks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('district', sa.String(length=20), nullable=False))
        batch_op.drop_column('address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blood_banks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', mysql.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('district')
        batch_op.drop_column('state')

    # ### end Alembic commands ###
