"""added dob to auto calculate age

Revision ID: dfae2f1b6bc5
Revises: 39ed7d739d02
Create Date: 2025-12-22 12:36:55.136005

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dfae2f1b6bc5'
down_revision = '39ed7d739d02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dob', sa.Date(), nullable=False))
        batch_op.drop_column('age')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('dob')

    # ### end Alembic commands ###
